/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkspaceRouteImport } from './routes/_app.workspace'
import { Route as AppUniverseRouteImport } from './routes/_app.universe'
import { Route as AppTerminalRouteImport } from './routes/_app.terminal'
import { Route as AppStrategiesRouteImport } from './routes/_app.strategies'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppScreenerRouteImport } from './routes/_app.screener'
import { Route as AppReplayRouteImport } from './routes/_app.replay'
import { Route as AppPortfolioRouteImport } from './routes/_app.portfolio'
import { Route as AppPerformanceRouteImport } from './routes/_app.performance'
import { Route as AppOrdersRouteImport } from './routes/_app.orders'
import { Route as AppNewsRouteImport } from './routes/_app.news'
import { Route as AppJournalRouteImport } from './routes/_app.journal'
import { Route as AppHeatmapRouteImport } from './routes/_app.heatmap'
import { Route as AppFuturesRouteImport } from './routes/_app.futures'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCompareRouteImport } from './routes/_app.compare'
import { Route as AppChartGridRouteImport } from './routes/_app.chart-grid'
import { Route as AppBacktestRouteImport } from './routes/_app.backtest'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'
import { Route as ApiMarketQuotesRouteImport } from './routes/api.market.quotes'
import { Route as ApiMarketCompanyRouteImport } from './routes/api.market.company'
import { Route as ApiMarketCompaniesRouteImport } from './routes/api.market.companies'
import { Route as ApiMarketCandlesRouteImport } from './routes/api.market.candles'
import { Route as AppStrategiesStrategyIdRouteImport } from './routes/_app.strategies.$strategyId'
import { Route as AppStockSymbolRouteImport } from './routes/_app.stock.$symbol'
import { Route as AppOptionsUnderlyingRouteImport } from './routes/_app.options.$underlying'
import { Route as AppChartSymbolRouteImport } from './routes/_app.chart.$symbol'
import { Route as AppAdminDataQualityRouteImport } from './routes/_app.admin.data-quality'
import { Route as AppStrategiesStrategyIdDeploymentsRouteImport } from './routes/_app.strategies.$strategyId.deployments'
import { Route as AppStrategiesStrategyIdBacktestsRouteImport } from './routes/_app.strategies.$strategyId.backtests'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppUniverseRoute = AppUniverseRouteImport.update({
  id: '/universe',
  path: '/universe',
  getParentRoute: () => AppRoute,
} as any)
const AppTerminalRoute = AppTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => AppRoute,
} as any)
const AppStrategiesRoute = AppStrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScreenerRoute = AppScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => AppRoute,
} as any)
const AppReplayRoute = AppReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsRoute = AppNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppHeatmapRoute = AppHeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => AppRoute,
} as any)
const AppFuturesRoute = AppFuturesRouteImport.update({
  id: '/futures',
  path: '/futures',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCompareRoute = AppCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppRoute,
} as any)
const AppChartGridRoute = AppChartGridRouteImport.update({
  id: '/chart-grid',
  path: '/chart-grid',
  getParentRoute: () => AppRoute,
} as any)
const AppBacktestRoute = AppBacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const ApiMarketQuotesRoute = ApiMarketQuotesRouteImport.update({
  id: '/api/market/quotes',
  path: '/api/market/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketCompanyRoute = ApiMarketCompanyRouteImport.update({
  id: '/api/market/company',
  path: '/api/market/company',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketCompaniesRoute = ApiMarketCompaniesRouteImport.update({
  id: '/api/market/companies',
  path: '/api/market/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketCandlesRoute = ApiMarketCandlesRouteImport.update({
  id: '/api/market/candles',
  path: '/api/market/candles',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStrategiesStrategyIdRoute = AppStrategiesStrategyIdRouteImport.update({
  id: '/$strategyId',
  path: '/$strategyId',
  getParentRoute: () => AppStrategiesRoute,
} as any)
const AppStockSymbolRoute = AppStockSymbolRouteImport.update({
  id: '/stock/$symbol',
  path: '/stock/$symbol',
  getParentRoute: () => AppRoute,
} as any)
const AppOptionsUnderlyingRoute = AppOptionsUnderlyingRouteImport.update({
  id: '/options/$underlying',
  path: '/options/$underlying',
  getParentRoute: () => AppRoute,
} as any)
const AppChartSymbolRoute = AppChartSymbolRouteImport.update({
  id: '/chart/$symbol',
  path: '/chart/$symbol',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDataQualityRoute = AppAdminDataQualityRouteImport.update({
  id: '/admin/data-quality',
  path: '/admin/data-quality',
  getParentRoute: () => AppRoute,
} as any)
const AppStrategiesStrategyIdDeploymentsRoute =
  AppStrategiesStrategyIdDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => AppStrategiesStrategyIdRoute,
  } as any)
const AppStrategiesStrategyIdBacktestsRoute =
  AppStrategiesStrategyIdBacktestsRouteImport.update({
    id: '/backtests',
    path: '/backtests',
    getParentRoute: () => AppStrategiesStrategyIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AppAlertsRoute
  '/backtest': typeof AppBacktestRoute
  '/chart-grid': typeof AppChartGridRoute
  '/compare': typeof AppCompareRoute
  '/dashboard': typeof AppDashboardRoute
  '/futures': typeof AppFuturesRoute
  '/heatmap': typeof AppHeatmapRoute
  '/journal': typeof AppJournalRoute
  '/news': typeof AppNewsRoute
  '/orders': typeof AppOrdersRoute
  '/performance': typeof AppPerformanceRoute
  '/portfolio': typeof AppPortfolioRoute
  '/replay': typeof AppReplayRoute
  '/screener': typeof AppScreenerRoute
  '/settings': typeof AppSettingsRoute
  '/strategies': typeof AppStrategiesRouteWithChildren
  '/terminal': typeof AppTerminalRoute
  '/universe': typeof AppUniverseRoute
  '/workspace': typeof AppWorkspaceRoute
  '/admin/data-quality': typeof AppAdminDataQualityRoute
  '/chart/$symbol': typeof AppChartSymbolRoute
  '/options/$underlying': typeof AppOptionsUnderlyingRoute
  '/stock/$symbol': typeof AppStockSymbolRoute
  '/strategies/$strategyId': typeof AppStrategiesStrategyIdRouteWithChildren
  '/api/market/candles': typeof ApiMarketCandlesRoute
  '/api/market/companies': typeof ApiMarketCompaniesRoute
  '/api/market/company': typeof ApiMarketCompanyRoute
  '/api/market/quotes': typeof ApiMarketQuotesRoute
  '/strategies/$strategyId/backtests': typeof AppStrategiesStrategyIdBacktestsRoute
  '/strategies/$strategyId/deployments': typeof AppStrategiesStrategyIdDeploymentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AppAlertsRoute
  '/backtest': typeof AppBacktestRoute
  '/chart-grid': typeof AppChartGridRoute
  '/compare': typeof AppCompareRoute
  '/dashboard': typeof AppDashboardRoute
  '/futures': typeof AppFuturesRoute
  '/heatmap': typeof AppHeatmapRoute
  '/journal': typeof AppJournalRoute
  '/news': typeof AppNewsRoute
  '/orders': typeof AppOrdersRoute
  '/performance': typeof AppPerformanceRoute
  '/portfolio': typeof AppPortfolioRoute
  '/replay': typeof AppReplayRoute
  '/screener': typeof AppScreenerRoute
  '/settings': typeof AppSettingsRoute
  '/strategies': typeof AppStrategiesRouteWithChildren
  '/terminal': typeof AppTerminalRoute
  '/universe': typeof AppUniverseRoute
  '/workspace': typeof AppWorkspaceRoute
  '/admin/data-quality': typeof AppAdminDataQualityRoute
  '/chart/$symbol': typeof AppChartSymbolRoute
  '/options/$underlying': typeof AppOptionsUnderlyingRoute
  '/stock/$symbol': typeof AppStockSymbolRoute
  '/strategies/$strategyId': typeof AppStrategiesStrategyIdRouteWithChildren
  '/api/market/candles': typeof ApiMarketCandlesRoute
  '/api/market/companies': typeof ApiMarketCompaniesRoute
  '/api/market/company': typeof ApiMarketCompanyRoute
  '/api/market/quotes': typeof ApiMarketQuotesRoute
  '/strategies/$strategyId/backtests': typeof AppStrategiesStrategyIdBacktestsRoute
  '/strategies/$strategyId/deployments': typeof AppStrategiesStrategyIdDeploymentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/backtest': typeof AppBacktestRoute
  '/_app/chart-grid': typeof AppChartGridRoute
  '/_app/compare': typeof AppCompareRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/futures': typeof AppFuturesRoute
  '/_app/heatmap': typeof AppHeatmapRoute
  '/_app/journal': typeof AppJournalRoute
  '/_app/news': typeof AppNewsRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/performance': typeof AppPerformanceRoute
  '/_app/portfolio': typeof AppPortfolioRoute
  '/_app/replay': typeof AppReplayRoute
  '/_app/screener': typeof AppScreenerRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/strategies': typeof AppStrategiesRouteWithChildren
  '/_app/terminal': typeof AppTerminalRoute
  '/_app/universe': typeof AppUniverseRoute
  '/_app/workspace': typeof AppWorkspaceRoute
  '/_app/admin/data-quality': typeof AppAdminDataQualityRoute
  '/_app/chart/$symbol': typeof AppChartSymbolRoute
  '/_app/options/$underlying': typeof AppOptionsUnderlyingRoute
  '/_app/stock/$symbol': typeof AppStockSymbolRoute
  '/_app/strategies/$strategyId': typeof AppStrategiesStrategyIdRouteWithChildren
  '/api/market/candles': typeof ApiMarketCandlesRoute
  '/api/market/companies': typeof ApiMarketCompaniesRoute
  '/api/market/company': typeof ApiMarketCompanyRoute
  '/api/market/quotes': typeof ApiMarketQuotesRoute
  '/_app/strategies/$strategyId/backtests': typeof AppStrategiesStrategyIdBacktestsRoute
  '/_app/strategies/$strategyId/deployments': typeof AppStrategiesStrategyIdDeploymentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/backtest'
    | '/chart-grid'
    | '/compare'
    | '/dashboard'
    | '/futures'
    | '/heatmap'
    | '/journal'
    | '/news'
    | '/orders'
    | '/performance'
    | '/portfolio'
    | '/replay'
    | '/screener'
    | '/settings'
    | '/strategies'
    | '/terminal'
    | '/universe'
    | '/workspace'
    | '/admin/data-quality'
    | '/chart/$symbol'
    | '/options/$underlying'
    | '/stock/$symbol'
    | '/strategies/$strategyId'
    | '/api/market/candles'
    | '/api/market/companies'
    | '/api/market/company'
    | '/api/market/quotes'
    | '/strategies/$strategyId/backtests'
    | '/strategies/$strategyId/deployments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/backtest'
    | '/chart-grid'
    | '/compare'
    | '/dashboard'
    | '/futures'
    | '/heatmap'
    | '/journal'
    | '/news'
    | '/orders'
    | '/performance'
    | '/portfolio'
    | '/replay'
    | '/screener'
    | '/settings'
    | '/strategies'
    | '/terminal'
    | '/universe'
    | '/workspace'
    | '/admin/data-quality'
    | '/chart/$symbol'
    | '/options/$underlying'
    | '/stock/$symbol'
    | '/strategies/$strategyId'
    | '/api/market/candles'
    | '/api/market/companies'
    | '/api/market/company'
    | '/api/market/quotes'
    | '/strategies/$strategyId/backtests'
    | '/strategies/$strategyId/deployments'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/alerts'
    | '/_app/backtest'
    | '/_app/chart-grid'
    | '/_app/compare'
    | '/_app/dashboard'
    | '/_app/futures'
    | '/_app/heatmap'
    | '/_app/journal'
    | '/_app/news'
    | '/_app/orders'
    | '/_app/performance'
    | '/_app/portfolio'
    | '/_app/replay'
    | '/_app/screener'
    | '/_app/settings'
    | '/_app/strategies'
    | '/_app/terminal'
    | '/_app/universe'
    | '/_app/workspace'
    | '/_app/admin/data-quality'
    | '/_app/chart/$symbol'
    | '/_app/options/$underlying'
    | '/_app/stock/$symbol'
    | '/_app/strategies/$strategyId'
    | '/api/market/candles'
    | '/api/market/companies'
    | '/api/market/company'
    | '/api/market/quotes'
    | '/_app/strategies/$strategyId/backtests'
    | '/_app/strategies/$strategyId/deployments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiMarketCandlesRoute: typeof ApiMarketCandlesRoute
  ApiMarketCompaniesRoute: typeof ApiMarketCompaniesRoute
  ApiMarketCompanyRoute: typeof ApiMarketCompanyRoute
  ApiMarketQuotesRoute: typeof ApiMarketQuotesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspace': {
      id: '/_app/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/universe': {
      id: '/_app/universe'
      path: '/universe'
      fullPath: '/universe'
      preLoaderRoute: typeof AppUniverseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/terminal': {
      id: '/_app/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof AppTerminalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/strategies': {
      id: '/_app/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof AppStrategiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/screener': {
      id: '/_app/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof AppScreenerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/replay': {
      id: '/_app/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof AppReplayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio': {
      id: '/_app/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance': {
      id: '/_app/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/news': {
      id: '/_app/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AppNewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal': {
      id: '/_app/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/heatmap': {
      id: '/_app/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof AppHeatmapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/futures': {
      id: '/_app/futures'
      path: '/futures'
      fullPath: '/futures'
      preLoaderRoute: typeof AppFuturesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compare': {
      id: '/_app/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AppCompareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chart-grid': {
      id: '/_app/chart-grid'
      path: '/chart-grid'
      fullPath: '/chart-grid'
      preLoaderRoute: typeof AppChartGridRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/backtest': {
      id: '/_app/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof AppBacktestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/market/quotes': {
      id: '/api/market/quotes'
      path: '/api/market/quotes'
      fullPath: '/api/market/quotes'
      preLoaderRoute: typeof ApiMarketQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/company': {
      id: '/api/market/company'
      path: '/api/market/company'
      fullPath: '/api/market/company'
      preLoaderRoute: typeof ApiMarketCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/companies': {
      id: '/api/market/companies'
      path: '/api/market/companies'
      fullPath: '/api/market/companies'
      preLoaderRoute: typeof ApiMarketCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/candles': {
      id: '/api/market/candles'
      path: '/api/market/candles'
      fullPath: '/api/market/candles'
      preLoaderRoute: typeof ApiMarketCandlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/strategies/$strategyId': {
      id: '/_app/strategies/$strategyId'
      path: '/$strategyId'
      fullPath: '/strategies/$strategyId'
      preLoaderRoute: typeof AppStrategiesStrategyIdRouteImport
      parentRoute: typeof AppStrategiesRoute
    }
    '/_app/stock/$symbol': {
      id: '/_app/stock/$symbol'
      path: '/stock/$symbol'
      fullPath: '/stock/$symbol'
      preLoaderRoute: typeof AppStockSymbolRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/options/$underlying': {
      id: '/_app/options/$underlying'
      path: '/options/$underlying'
      fullPath: '/options/$underlying'
      preLoaderRoute: typeof AppOptionsUnderlyingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chart/$symbol': {
      id: '/_app/chart/$symbol'
      path: '/chart/$symbol'
      fullPath: '/chart/$symbol'
      preLoaderRoute: typeof AppChartSymbolRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/data-quality': {
      id: '/_app/admin/data-quality'
      path: '/admin/data-quality'
      fullPath: '/admin/data-quality'
      preLoaderRoute: typeof AppAdminDataQualityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/strategies/$strategyId/deployments': {
      id: '/_app/strategies/$strategyId/deployments'
      path: '/deployments'
      fullPath: '/strategies/$strategyId/deployments'
      preLoaderRoute: typeof AppStrategiesStrategyIdDeploymentsRouteImport
      parentRoute: typeof AppStrategiesStrategyIdRoute
    }
    '/_app/strategies/$strategyId/backtests': {
      id: '/_app/strategies/$strategyId/backtests'
      path: '/backtests'
      fullPath: '/strategies/$strategyId/backtests'
      preLoaderRoute: typeof AppStrategiesStrategyIdBacktestsRouteImport
      parentRoute: typeof AppStrategiesStrategyIdRoute
    }
  }
}

interface AppStrategiesStrategyIdRouteChildren {
  AppStrategiesStrategyIdBacktestsRoute: typeof AppStrategiesStrategyIdBacktestsRoute
  AppStrategiesStrategyIdDeploymentsRoute: typeof AppStrategiesStrategyIdDeploymentsRoute
}

const AppStrategiesStrategyIdRouteChildren: AppStrategiesStrategyIdRouteChildren =
  {
    AppStrategiesStrategyIdBacktestsRoute:
      AppStrategiesStrategyIdBacktestsRoute,
    AppStrategiesStrategyIdDeploymentsRoute:
      AppStrategiesStrategyIdDeploymentsRoute,
  }

const AppStrategiesStrategyIdRouteWithChildren =
  AppStrategiesStrategyIdRoute._addFileChildren(
    AppStrategiesStrategyIdRouteChildren,
  )

interface AppStrategiesRouteChildren {
  AppStrategiesStrategyIdRoute: typeof AppStrategiesStrategyIdRouteWithChildren
}

const AppStrategiesRouteChildren: AppStrategiesRouteChildren = {
  AppStrategiesStrategyIdRoute: AppStrategiesStrategyIdRouteWithChildren,
}

const AppStrategiesRouteWithChildren = AppStrategiesRoute._addFileChildren(
  AppStrategiesRouteChildren,
)

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppBacktestRoute: typeof AppBacktestRoute
  AppChartGridRoute: typeof AppChartGridRoute
  AppCompareRoute: typeof AppCompareRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFuturesRoute: typeof AppFuturesRoute
  AppHeatmapRoute: typeof AppHeatmapRoute
  AppJournalRoute: typeof AppJournalRoute
  AppNewsRoute: typeof AppNewsRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppReplayRoute: typeof AppReplayRoute
  AppScreenerRoute: typeof AppScreenerRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStrategiesRoute: typeof AppStrategiesRouteWithChildren
  AppTerminalRoute: typeof AppTerminalRoute
  AppUniverseRoute: typeof AppUniverseRoute
  AppWorkspaceRoute: typeof AppWorkspaceRoute
  AppAdminDataQualityRoute: typeof AppAdminDataQualityRoute
  AppChartSymbolRoute: typeof AppChartSymbolRoute
  AppOptionsUnderlyingRoute: typeof AppOptionsUnderlyingRoute
  AppStockSymbolRoute: typeof AppStockSymbolRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppBacktestRoute: AppBacktestRoute,
  AppChartGridRoute: AppChartGridRoute,
  AppCompareRoute: AppCompareRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFuturesRoute: AppFuturesRoute,
  AppHeatmapRoute: AppHeatmapRoute,
  AppJournalRoute: AppJournalRoute,
  AppNewsRoute: AppNewsRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppReplayRoute: AppReplayRoute,
  AppScreenerRoute: AppScreenerRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStrategiesRoute: AppStrategiesRouteWithChildren,
  AppTerminalRoute: AppTerminalRoute,
  AppUniverseRoute: AppUniverseRoute,
  AppWorkspaceRoute: AppWorkspaceRoute,
  AppAdminDataQualityRoute: AppAdminDataQualityRoute,
  AppChartSymbolRoute: AppChartSymbolRoute,
  AppOptionsUnderlyingRoute: AppOptionsUnderlyingRoute,
  AppStockSymbolRoute: AppStockSymbolRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiMarketCandlesRoute: ApiMarketCandlesRoute,
  ApiMarketCompaniesRoute: ApiMarketCompaniesRoute,
  ApiMarketCompanyRoute: ApiMarketCompanyRoute,
  ApiMarketQuotesRoute: ApiMarketQuotesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
